In [23]:
import pandas as pd
import matplotlib.pyplot as plt

df  = pd.read_csv("Covid19_dataset.csv")
df.head()

    Entity Code         Day  Baseline expected deaths  Reported deaths
0  Albania  ALB  2020-01-31                    2434.2           2187.0
1  Albania  ALB  2020-02-29                    1961.6           2018.0
2  Albania  ALB  2020-03-31                    1967.2           1993.0
3  Albania  ALB  2020-04-30                    1734.0           1804.0
4  Albania  ALB  2020-05-31                    1685.0           1803.0

In [24]:
df.tail()

           Entity Code         Day  Baseline expected deaths  Reported deaths
15090  Uzbekistan  UZB  2023-08-31                   12512.4          18877.0
15091  Uzbekistan  UZB  2023-09-30                   11116.8          13691.0
15092  Uzbekistan  UZB  2023-10-31                   12177.4          13789.0
15093  Uzbekistan  UZB  2023-11-30                   13090.0          13428.0
15094  Uzbekistan  UZB  2023-12-31                   18996.0          15876.0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15095 entries, 0 to 15094
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Entity                    15095 non-null  object
 1   Code                      14468 non-null  object
 2   Day                       15095 non-null  object
 3   Baseline expected deaths  14468 non-null  float64
 4   Reported deaths           14434 non-null  float64
dtypes: float64(2), object(3)
memory usage: 589.8+ KB

In [26]:
df.isnull().sum()

Entity                        0
Code                        627
Day                           0
Baseline expected deaths    627
Reported deaths             661
dtype: int64

In [27]:
df.describe()

       Baseline expected deaths  Reported deaths
count              14468.000000     14434.000000
mean                5962.225650      6686.724699
std                15433.955296     17640.832533
min                   10.600000         7.000000
25%                  400.050000       445.000000
50%                 1652.700000      1758.500000
75%                 4905.550000      5739.275000
max               166545.100000    266343.000000

In [28]:
df.shape

(15095, 5)

In [29]:
df.columns

Index(['Entity', 'Code', 'Day', 'Baseline expected deaths', 'Reported deaths'], dtype='object')

# Cleaning the dataset

In [30]:
df["date"] = pd.to_datetime(df["Day"])
df

,Entity,Code,Day,Baseline expected deaths,Reported deaths,date
0,Albania,ALB,2020-01-31,2434.2,2187.0,2020-01-31
1,Albania,ALB,2020-02-29,1961.6,2018.0,2020-02-29
2,Albania,ALB,2020-03-31,1967.2,1993.0,2020-03-31
3,Albania,ALB,2020-04-30,1734.0,1804.0,2020-04-30
4,Albania,ALB,2020-05-31,1685.0,1803.0,2020-05-31
...,...,...,...,...,...,...
15090,Uzbekistan,UZB,2023-08-31,12512.4,18877.0,2023-08-31
15091,Uzbekistan,UZB,2023-09-30,11116.8,13691.0,2023-09-30
15092,Uzbekistan,UZB,2023-10-31,12177.4,13789.0,2023-10-31
15093,Uzbekistan,UZB,2023-11-30,13090.0,13428.0,2023-11-30
15094,Uzbekistan,UZB,2023-12-31,18996.0,15876.0,2023-12-31

In [31]:
df = df.drop(columns = ["Day"])

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df = df.dropna()

In [34]:
df.isnull().sum()

Entity                      0
Code                        0
Baseline expected deaths    0
Reported deaths             0
date                        0
dtype: int64

##### Total rows

In [36]:
print("The Total Number of Rows is : " , df.shape[0])

The Total Number of Rows is :  13807

##### Total columns

In [37]:
print("The Total Number of Columns is : " , df.shape[1])

The Total Number of Columns is :  5

##### Number of countries

In [40]:
print("The Total Number of Country are :" , df["Entity"].nunique())

The Total Number of Country are : 127

##### Earliest date

In [44]:
print("The Earliest Date is : ", df["date"].min())

The Earliest Date is :  2020-01-05 00:00:00

##### Latest date

In [45]:
print("The Latest date is : " , df["date"].max())

The Latest date is :  2023-12-31 00:00:00

In [47]:
df["Excess Deaths"] = df["Reported deaths"] - df["Baseline expected deaths"]