📅 Day 19 – GroupBy (Pandas)
groupby() is one of the most important functions in Pandas. It helps you analyze data category-wise.

📚 Learn
1️⃣ Total Sales by Category
df.groupby("Category")["Sales"].sum()
Example Output
Category
Furniture         50000
Office Supplies   70000
Technology        90000
2️⃣ Average Sales by Category
df.groupby("Category")["Sales"].mean()
Example Output
Category
Furniture         2500
Office Supplies   1800
Technology        3200
3️⃣ Count Records
df.groupby("Category").size()
Example Output
Category
Furniture         20
Office Supplies   40
Technology        28
4️⃣ Multiple Aggregations
df.groupby("Category")["Sales"].agg(["sum", "mean", "max", "min"])

Output:

                  sum   mean    max   min
Category
Furniture       50000  2500   9000   200
Technology      90000  3200  12000   500
💻 Practice Exercises

Use your existing datasets (sales_data.csv, customer_dataset.csv, amazon.csv) if applicable.

In [6]:
import pandas as pd

df = pd.read_csv("sales_data.csv")

print(df.head())

   Product_ID   Sale_Date Sales_Rep Region  Sales_Amount  Quantity_Sold  \
0        1052  2023-02-03       Bob  North       5053.97             18
1        1093  2023-04-21       Bob   West       4384.02             17
2        1015  2023-09-21     David  South       4631.23             30
3        1072  2023-08-24       Bob  South       2167.94             39
4        1061  2023-03-24   Charlie   East       3750.20             13

  Product_Category  Unit_Cost  Unit_Price Customer_Type  Discount  \
0        Furniture     152.75      267.22     Returning      0.09
1        Furniture    3816.39     4209.44     Returning      0.11
2             Food     261.56      371.40     Returning      0.20
3         Clothing    4330.03     4467.75           New      0.02
4      Electronics     637.37      692.71           New      0.08

  Payment_Method Sales_Channel Region_and_Sales_Rep
0           Cash        Online            North-Bob
1           Cash        Retail             West-Bob
2  Bank Transfer        Retail          South-David
3    Credit Card        Retail            South-Bob
4    Credit Card        Online         East-Charlie

In [8]:
# Find the total sales amount for each product category.
df.groupby("Product_Category")["Sales_Amount"].sum()

Product_Category
Clothing       1313474.36
Electronics    1243499.64
Food           1201773.54
Furniture      1260517.69
Name: Sales_Amount, dtype: float64

In [9]:
# Find the average sales amount for each product category.
df.groupby("Product_Category")["Sales_Amount"].mean()

Product_Category
Clothing       4901.023731
Electronics    5054.876585
Food           5317.582035
Furniture      4848.144962
Name: Sales_Amount, dtype: float64

In [10]:
# Count the number of orders in each region.
df.groupby("Region").size()

Region
East     263
North    267
South    226
West     244
dtype: int64

In [11]:
# Find the total quantity sold in each region.
df.groupby("Region")["Quantity_Sold"].sum()

Region
East     6356
North    6705
South    5808
West     6486
Name: Quantity_Sold, dtype: int64

In [12]:
# Count the number of sales made by each sales representative.
df.groupby("Sales_Rep").size()

Sales_Rep
Alice      192
Bob        208
Charlie    169
David      222
Eve        209
dtype: int64

In [13]:
# Find the average discount offered in each product category
df.groupby("Product_Category")["Discount"].mean()

Product_Category
Clothing       0.160224
Electronics    0.136504
Food           0.153805
Furniture      0.158115
Name: Discount, dtype: float64

In [14]:
# Find the total sales amount for each sales channel.
df.groupby("Sales_Channel")["Sales_Amount"].sum()

Sales_Channel
Online    2458833.93
Retail    2560431.30
Name: Sales_Amount, dtype: float64

In [15]:
# Find the average quantity sold for each customer type.
df.groupby("Customer_Type")["Quantity_Sold"].mean()

Customer_Type
New          26.158730
Returning    24.538306
Name: Quantity_Sold, dtype: float64

In [16]:
# Find the total sales amount by payment method.
df.groupby("Payment_Method")["Sales_Amount"].sum()

Payment_Method
Bank Transfer    1717363.17
Cash             1544338.54
Credit Card      1757563.52
Name: Sales_Amount, dtype: float64

In [17]:
# Find the average unit price for each product category.
df.groupby("Product_Category")["Unit_Price"].mean()

Product_Category
Clothing       2721.256381
Electronics    2795.207195
Food           2657.811726
Furniture      2734.065346
Name: Unit_Price, dtype: float64

In [18]:
# Find total sales amount and total quantity sold for each product category.
df.groupby("Product_Category")[["Sales_Amount", "Quantity_Sold"]].sum()

                  Sales_Amount  Quantity_Sold
Product_Category
Clothing            1313474.36           6922
Electronics         1243499.64           6096
Food                1201773.54           5608
Furniture           1260517.69           6729

In [19]:
# Find average sales amount and average discount by region.
df.groupby("Region")[["Sales_Amount", "Discount"]].mean()

        Sales_Amount  Discount
Region
East     4790.087186  0.162548
North    5129.634869  0.149551
South    5107.304690  0.148319
West     5063.971025  0.148320

In [20]:
# Find the top 3 regions with the highest sales amount.
df.groupby("Region")["Sales_Amount"] \
  .sum() \
  .sort_values(ascending=False) \
  .head(3)

Region
North    1369612.51
East     1259792.93
West     1235608.93
Name: Sales_Amount, dtype: float64

In [21]:
# Find the sales representative with the highest total sales
df.groupby("Sales_Rep")["Sales_Amount"] \
  .sum() \
  .sort_values(ascending=False) \
  .head(1)

Sales_Rep
David    1141737.36
Name: Sales_Amount, dtype: float64

In [22]:
# Find the payment method used the most.
df.groupby("Payment_Method") \
  .size() \
  .sort_values(ascending=False) \
  .head(1)

Payment_Method
Credit Card    345
dtype: int64

In [23]:
# Find total sales amount for each combination of region and sales channel.
df.groupby(["Region", "Sales_Channel"])["Sales_Amount"].sum()

Region  Sales_Channel
East    Online           575222.27
        Retail           684570.66
North   Online           683133.46
        Retail           686479.05
South   Online           590593.38
        Retail           563657.48
West    Online           609884.82
        Retail           625724.11
Name: Sales_Amount, dtype: float64

In [24]:
# Find the average sales amount for each customer type in each region.
df.groupby(["Customer_Type", "Region"])["Sales_Amount"].mean()

Customer_Type  Region
New            East      4920.203551
               North     5258.698966
               South     4985.327885
               West      4669.100513
Returning      East      4646.438720
               North     4976.239016
               South     5211.284918
               West      5427.749370
Name: Sales_Amount, dtype: float64

In [26]:
# Find the total sales amount generated by each sales representative in every region.
df.groupby(["Region", "Sales_Rep"])["Sales_Amount"].sum()

Region  Sales_Rep
East    Alice        260789.47
        Bob          309876.11
        Charlie      165172.94
        David        284613.51
        Eve          239340.90
North   Alice        249647.22
        Bob          233464.81
        Charlie      299789.01
        David        282539.27
        Eve          304172.20
South   Alice        239414.54
        Bob          251200.43
        Charlie      156140.68
        David        311416.99
        Eve          196078.22
West    Alice        215690.54
        Bob          286449.28
        Charlie      239708.85
        David        263167.59
        Eve          230592.67
Name: Sales_Amount, dtype: float64

In [27]:
# Find the product category with the highest sales amount.
df.groupby("Product_Category")["Sales_Amount"] \
  .sum() \
  .sort_values(ascending=False) \
  .head(1)

Product_Category
Clothing    1313474.36
Name: Sales_Amount, dtype: float64

In [28]:
# Find the region that sold the highest quantity of products.
df.groupby("Region")["Quantity_Sold"] \
  .sum() \
  .sort_values(ascending=False) \
  .head(1)

Region
North    6705
Name: Quantity_Sold, dtype: int64