In [168]:
import pandas as pd

df = pd.read_csv('train.csv')

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [169]:
print(df.info())
print(df.describe())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200
(891, 12)

In [170]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [171]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [172]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [173]:
df.duplicated().sum()

np.int64(0)

In [174]:
df['PassengerId'].duplicated().sum()

np.int64(0)

In [175]:
df = df.drop(columns = ['PassengerId'])

In [176]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [177]:
df['Title'] = df['Name'].str.extract(r",\s*([^.]*)\.")

In [178]:
df['Title'].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [179]:
df = df.drop(columns=["Ticket"])

In [180]:
df["HasCabin"] = df["Cabin"].notna().astype(int)
df[["Cabin", "HasCabin"]].head()

  Cabin  HasCabin
0   NaN         0
1   C85         1
2   NaN         0
3  C123         1
4   NaN         0

In [181]:
df = df.drop(columns=["Cabin"])

In [182]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [183]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [184]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [185]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)

In [186]:
df[["SibSp", "Parch", "FamilySize", "IsAlone"]].head(10)

   SibSp  Parch  FamilySize  IsAlone
0      1      0           2        0
1      1      0           2        0
2      0      0           1        1
3      1      0           2        0
4      0      0           1        1
5      0      0           1        1
6      0      0           1        1
7      3      1           5        0
8      0      2           3        0
9      1      0           2        0

In [187]:
df["Title"].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [188]:
df['Title'] = df['Title'].replace({
    'Mlle' : 'Miss' , 
    'Ms' : 'Miss' , 
    'Mme' : 'Mrs' })

In [189]:
title_counts  = df['Title'].value_counts()

rare_title = title_counts[title_counts < 10].index

df['Title'] = df['Title'].replace(rare_title, 'Rare')

In [190]:
df["Title"].value_counts()

Title
Mr        517
Miss      185
Mrs       126
Master     40
Rare       23
Name: count, dtype: int64

In [191]:
df = df.drop(columns = ['Name'])

In [192]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked', 'Title', 'HasCabin', 'FamilySize', 'IsAlone'],
      dtype='object')

In [193]:
y = df['Survived']

In [194]:
print(df.columns)
print(df.shape)

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked', 'Title', 'HasCabin', 'FamilySize', 'IsAlone'],
      dtype='object')
(891, 12)

In [165]:
print(df.isnull().sum())

Survived      0
Pclass        0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Embarked      0
Title         0
HasCabin      0
FamilySize    0
IsAlone       0
dtype: int64

In [60]:
from sklearn.preprocessing import LabelEncoder 

encoder = LabelEncoder() 

df['Sex_encoded'] = encoder.fit_transform(df['Sex'])

In [61]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()

df[['Pclass_encoded']] = encoder.fit_transform(df[['Pclass']])

In [62]:
X = df.copy()
y = y.copy()

In [63]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42  , stratify = y )

In [66]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(712, 14)
(712,)
(179, 14)
(179,)

In [82]:
numerical_features = ['Age' , "SibSp" , 'Parch' , 'Fare' , 'FamilySize']
categorical_features = ['Sex' , 'Embarked' , 'Title']
ordinal_features = ['Pclass']
binary_features = ['IsAlone' , 'HasCabin']

# print(X_train[numerical_features].dtypes)
# print(X_train[categorical_features].dtypes)
# print(X_train[ordinal_features].dtypes)
# print(X_train[binary_features].dtypes)

In [83]:
from sklearn.pipeline import Pipeline 
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

numeric_pipeline  = Pipeline([
    ('imputer' , SimpleImputer(strategy = 'median')) , 
    ('scaler' , StandardScaler()) ])

In [84]:
from sklearn.preprocessing import OneHotEncoder

categorical_pipeline  = Pipeline([
    ('imputer' , SimpleImputer(strategy = 'most_frequent')) , 
    ('encoder' , OneHotEncoder(handle_unknown = 'ignore'))
])

In [85]:
ordinal_pipeline = Pipeline([
    ('imputer' , SimpleImputer(strategy = 'most_frequent')) , 
    ('encoder' , OrdinalEncoder())
])

In [86]:
from sklearn.compose import ColumnTransformer 

preprocessor = ColumnTransformer([
    ('num' , numeric_pipeline , numerical_features) , 
    ('cat' , categorical_pipeline , categorical_features) , 
    ('ord' , ordinal_pipeline , ordinal_features) , 
    ('binary' , 'passthrough' , binary_features)
])

In [87]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [80]:
print("X_train columns:")
print(X_train.columns.tolist())

X_train columns:
['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Title', 'HasCabin', 'FamilySize', 'IsAlone', 'Sex_encoded', 'Pclass_encoded']

In [81]:
print("Numeric:", numerical_features)
print("Categorical:", categorical_features)
print("Ordinal:", ordinal_features)
print("Binary:", binary_features)

Numeric: ['Age', 'Sibsp', 'Parch', 'Fare', 'FamilySize']
Categorical: ['Sex', 'Embarked', 'Title']
Ordinal: ['Pclass']
Binary: ['IsAlone', 'HasCabin']

In [88]:
X = df.drop(columns=["Survived", "Sex_encoded", "Pclass_encoded"])
y = df["Survived"]

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [90]:
print(X_train.columns.tolist())
print(X_train.shape)

['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Title', 'HasCabin', 'FamilySize', 'IsAlone']
(712, 11)

In [91]:
numeric_features = [
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "FamilySize"
]

categorical_features = [
    "Sex",
    "Embarked",
    "Title"
]

ordinal_features = [
    "Pclass"
]

binary_features = [
    "IsAlone",
    "HasCabin"
]

In [92]:
print(X_train.columns.tolist())
print(X_train.shape)
print(X_test.shape)

['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'Title', 'HasCabin', 'FamilySize', 'IsAlone']
(712, 11)
(179, 11)

In [93]:
numeric_features = [
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "FamilySize"
]

categorical_features = [
    "Sex",
    "Embarked",
    "Title"
]

ordinal_features = [
    "Pclass"
]

binary_features = [
    "IsAlone",
    "HasCabin"
]

In [94]:
preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features),
    ("ord", ordinal_pipeline, ordinal_features),
    ("binary", "passthrough", binary_features)
])

In [95]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [96]:
print(X_train_processed.shape)
print(X_test_processed.shape)

(712, 18)
(179, 18)

In [97]:
feature_names = preprocessor.get_feature_names_out()

print(feature_names)
print(len(feature_names))

['num__Age' 'num__SibSp' 'num__Parch' 'num__Fare' 'num__FamilySize'
 'cat__Sex_female' 'cat__Sex_male' 'cat__Embarked_C' 'cat__Embarked_Q'
 'cat__Embarked_S' 'cat__Title_Master' 'cat__Title_Miss' 'cat__Title_Mr'
 'cat__Title_Mrs' 'cat__Title_Rare' 'ord__Pclass' 'binary__IsAlone'
 'binary__HasCabin']
18

In [98]:
from sklearn.linear_model import LogisticRegression

model_pipeline = Pipeline([
    ('preprocessor' , preprocessor) , 
    ('model' , LogisticRegression(max_iter = 1000))
])

In [99]:
model_pipeline.fit(X_train , y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age', 'SibSp', 'Parch',
                                                   'Fare', 'FamilySize']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked', 'Title']),
                                                 ('ord',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder())]),
                                                  ['Pclass']),
                                                 ('binary', 'passthrough',
                                                  ['IsAlone', 'HasCabin'])])),
                ('model', LogisticRegression(max_iter=1000))])

In [100]:
y_pred = model_pipeline.predict(X_test)
print(y_pred[:10])

[0 0 0 0 1 1 1 1 0 0]

In [101]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report 

print("Accuracy : " , accuracy_score(y_test, y_pred))

print("Classification Report : " , classification_report(y_test , y_pred))

print("Confusion Matrix :" , confusion_matrix(y_test , y_pred))

Accuracy :  0.8324022346368715
Classification Report :                precision    recall  f1-score   support

           0       0.85      0.88      0.87       110
           1       0.80      0.75      0.78        69

    accuracy                           0.83       179
   macro avg       0.83      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179

Confusion Matrix : [[97 13]
 [17 52]]

ValueError: could not convert string to float: 'male'

In [107]:
data = {
    "Age": [22, 25, None, 30, None],
    "Fare": [7.5, None, 15.0, 20.0, 12.0],
    "Sex": ["male", "female", "male", None, "female"]
}
df = pd.DataFrame(data)

df.isnull().sum()
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df['Sex'] = df['Sex'].fillna(df['Sex'].mode()[0])
df.isnull().sum()
df

    Age  Fare     Sex
0  22.0   7.5    male
1  25.0  13.5  female
2  25.0  15.0    male
3  30.0  20.0  female
4  25.0  12.0  female

In [108]:
data = {
    "Sex": ["male", "female", "female", "male", "female"],
    "Embarked": ["S", "C", "S", "Q", "C"],
    "Education": ["High School", "Bachelor", "Master", "PhD", "Bachelor"]
}

df = pd.DataFrame(data)

In [113]:
from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder

encoder = OneHotEncoder(sparse_output = False)

X_encoded = encoder.fit_transform(df[['Sex' , 'Embarked']])

ordinal_encoder = OrdinalEncoder(
    categories = [['High School' , 'Bachelor' , 'Master' , 'PhD' ]]
)

X_education = encoder.fit_transform(df[['Education']])

In [114]:
data = {
    "Age": [20, 25, 30, 35, 40],
    "Fare": [10, 20, 30, 40, 50]
}

df = pd.DataFrame(data)

In [118]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler 

standardscaler = StandardScaler()
minmaxscaler = MinMaxScaler()

X_standard = standardscaler.fit_transform(df[['Age' , 'Fare']])
X_minmax = minmaxscaler.fit_transform(df[['Age' , 'Fare']])

print("StandardScaler : " , X_standard)
print("MinMaxScaler : " , X_minmax)

StandardScaler :  [[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]
MinMaxScaler :  [[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]]

In [119]:
data = {
    "SibSp": [1, 0, 3, 0, 1],
    "Parch": [0, 0, 1, 2, 0]
}

df = pd.DataFrame(data)

In [122]:
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['IsAlone'] = (df['FamilySize'] == 1).astype(int)
df

   SibSp  Parch  FamilySize  IsAlone
0      1      0           2        0
1      0      0           1        1
2      3      1           5        0
3      0      2           3        0
4      1      0           2        0

In [123]:
data = {
    "Age": [22, 30, None, 40, 28],
    "Fare": [7.5, 20.0, 15.0, None, 30.0]
}

df = pd.DataFrame(data)

In [131]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler
import numpy as np 


pipeline = Pipeline([
    ('imputer' , SimpleImputer(strategy = 'median')) , 
    ('scaler' , StandardScaler())
])

df_transformed = pipeline.fit_transform(df)
print(df_transformed)
df_transformed = pd.DataFrame(df_transformed , columns =df.columns)
print(df_transformed.isnull().sum())

[[-1.34243536 -1.43553045]
 [ 0.03442142  0.27343437]
 [-0.13768568 -0.41015156]
 [ 1.7554924  -0.06835859]
 [-0.30979278  1.64060622]]
Age     0
Fare    0
dtype: int64

In [132]:
data = {
    "Age": [22, 30, None, 40, 28],
    "Fare": [7.5, 20.0, 15.0, None, 30.0],
    "Sex": ["male", "female", "male", "female", "male"],
    "Embarked": ["S", "C", "S", None, "Q"]
}

df = pd.DataFrame(data)

In [136]:
from sklearn.pipeline import Pipeline 
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler , OneHotEncoder
from sklearn.linear_model import LinearRegression

numerical_columns = ['Age' , 'Fare']
categorical_columns = ['Sex' , 'Embarked']


numerical_pipeline = Pipeline([
    ('imputer' , SimpleImputer(strategy = 'median')) , 
    ('scaler' , StandardScaler())
])

categorical_pipeline = Pipeline([
    ('imputer' , SimpleImputer(strategy = 'most_frequent')) , 
    ('encoder' , OneHotEncoder())
])

preprocessor = ColumnTransformer([
    ('num' , numerical_pipeline , numerical_columns) , 
    ('cat' , categorical_pipeline , categorical_columns)
])

X_processed = preprocessor.fit_transform(df)

print(X_processed.shape)
print(preprocessor.get_feature_names_out())

(5, 8)
['num__Age' 'num__Fare' 'cat__Sex_female' 'cat__Sex_male'
 'cat__Embarked_C' 'cat__Embarked_Q' 'cat__Embarked_S'
 'cat__Embarked_None']

In [195]:

X = df.drop(columns = ['Survived'])
y = df['Survived']
X

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title,HasCabin,FamilySize,IsAlone
0,3,male,22.0,1,0,7.2500,S,Mr,0,2,0
1,1,female,38.0,1,0,71.2833,C,Mrs,1,2,0
2,3,female,26.0,0,0,7.9250,S,Miss,0,1,1
3,1,female,35.0,1,0,53.1000,S,Mrs,1,2,0
4,3,male,35.0,0,0,8.0500,S,Mr,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...
886,2,male,27.0,0,0,13.0000,S,Rare,0,1,1
887,1,female,19.0,0,0,30.0000,S,Miss,1,1,1
888,3,female,28.0,1,2,23.4500,S,Miss,0,4,0
889,1,male,26.0,0,0,30.0000,C,Mr,1,1,1
890,3,male,32.0,0,0,7.7500,Q,Mr,0,1,1

In [210]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler , OneHotEncoder , OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X , y , random_state = 42 , test_size = 0.2)

numerical_columns = ['Age' , 'SibSp' , 'Parch' ,'Fare' , 'FamilySize']

categorical_columns = ['Sex' , 'Embarked' , 'Title']

ordinal_columns = ['Pclass']

binary_columns = ['IsAlone' , 'HasCabin']

numerical_pipeline =  Pipeline([
    ('imputer' , SimpleImputer(strategy = 'median')), 
    ('scaler' , StandardScaler())
])

categorical_pipeline = Pipeline([
    ('imputer' , SimpleImputer(strategy = 'most_frequent')) , 
    ('encoder' , OneHotEncoder())
])

ordinal_pipeline = Pipeline([
    ('encoder' , OrdinalEncoder())
])



preprocessor = ColumnTransformer([
    ('num' , numerical_pipeline , numerical_columns ) , 
    ('cat' , categorical_pipeline , categorical_columns ) , 
    ('ord' , ordinal_pipeline , ordinal_columns) , 
    ('binary' , 'passthrough' , binary_columns)
])

model_pipeline = Pipeline([
    ('preprocessor' , preprocessor) , 
    ('model' , LogisticRegression())
])

model_pipeline.fit(X_train , y_train)

y_pred = model_pipeline.predict(X_test)
print(y_pred[:10])
print(model_pipeline.score(X_test, y_test))
print(model_pipeline.named_steps)
features_names = model_pipeline.named_steps['preprocessor'].get_feature_names_out()

print(features_names)
print('Total Features :' , len(features_names))

[1 0 0 1 1 1 1 0 1 1]
0.8324022346368715
{'preprocessor': ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['Age', 'SibSp', 'Parch', 'Fare',
                                  'FamilySize']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder', OneHotEncoder())]),
                                 ['Sex', 'Embarked', 'Title']),
                                ('ord',
                                 Pipeline(steps=[('encoder',
                                                  OrdinalEncoder())]),
                                 ['Pclass']),
                                ('binary', 'passthrough',
                                 ['IsAlone', 'HasCabin'])]), 'model': LogisticRegression()}
['num__Age' 'num__SibSp' 'num__Parch' 'num__Fare' 'num__FamilySize'
 'cat__Sex_female' 'cat__Sex_male' 'cat__Embarked_C' 'cat__Embarked_Q'
 'cat__Embarked_S' 'cat__Title_Master' 'cat__Title_Miss' 'cat__Title_Mr'
 'cat__Title_Mrs' 'cat__Title_Rare' 'ord__Pclass' 'binary__IsAlone'
 'binary__HasCabin']
Total Features : 18

In [211]:
feature_names = model_pipeline.named_steps[
    "preprocessor"
].get_feature_names_out()

for i , feature in enumerate(feature_names , start = 1):
    print(i , feature)

1 num__Age
2 num__SibSp
3 num__Parch
4 num__Fare
5 num__FamilySize
6 cat__Sex_female
7 cat__Sex_male
8 cat__Embarked_C
9 cat__Embarked_Q
10 cat__Embarked_S
11 cat__Title_Master
12 cat__Title_Miss
13 cat__Title_Mr
14 cat__Title_Mrs
15 cat__Title_Rare
16 ord__Pclass
17 binary__IsAlone
18 binary__HasCabin

In [217]:
import joblib

joblib.dump(
    model_pipeline , 
    'titanic_model_pipeline.pkl'
)

['titanic_model_pipeline.pkl']

In [218]:
model_pipeline = joblib.load('titanic_model_pipeline.pkl')

In [220]:
# new_data = []
# predictions = model_pipeline.predict(new_data)