In [132]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
#Loading the dataset
df = pd.read_csv("hotel_bookings.csv")

# Display first 10 rows
df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

In [3]:
# Display last 5 rows
df.tail()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [4]:
df.shape

(119390, 32)

In [5]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [7]:
# Displaying only Numberic Columns
df.select_dtypes(include = ["number"] ).columns

Index(['is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_week_number', 'arrival_date_day_of_month',
       'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children',
       'babies', 'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'booking_changes', 'agent', 'company',
       'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
       'total_of_special_requests'],
      dtype='object')

In [8]:
# Displaying Only Categorial Columns 
df.select_dtypes(include = [object]).columns

Index(['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment',
       'distribution_channel', 'reserved_room_type', 'assigned_room_type',
       'deposit_type', 'customer_type', 'reservation_status',
       'reservation_status_date'],
      dtype='object')

In [9]:
# Displaying only Boolean Columns 
df.select_dtypes(include = [ "boolean" ] ).columns

Index([], dtype='object')

In [10]:
# Total Number of numerical columns are in the dataset.
df.select_dtypes(include = ["number"]).shape[1]

20

In [11]:
# Total Number of categorical (object) columns are in the dataset.
df.select_dtypes(include = ["object"]).shape[1]

12

In [27]:
# the missing-value percentage for every column and sort it from highest to lowest.
((df.isnull().sum() / len(df))*100).round(2).sort_values(ascending = False)

company                           94.31
agent                             13.69
country                            0.41
hotel                              0.00
arrival_date_month                 0.00
arrival_date_week_number           0.00
lead_time                          0.00
is_canceled                        0.00
stays_in_weekend_nights            0.00
stays_in_week_nights               0.00
children                           0.00
adults                             0.00
babies                             0.00
meal                               0.00
arrival_date_day_of_month          0.00
arrival_date_year                  0.00
distribution_channel               0.00
market_segment                     0.00
previous_bookings_not_canceled     0.00
is_repeated_guest                  0.00
reserved_room_type                 0.00
assigned_room_type                 0.00
booking_changes                    0.00
previous_cancellations             0.00
deposit_type                       0.00
days_in_waiting_list               0.00
customer_type                      0.00
adr                                0.00
required_car_parking_spaces        0.00
total_of_special_requests          0.00
reservation_status                 0.00
reservation_status_date            0.00
dtype: float64

In [41]:
# columns that have at least one missing value.
missing = df.isnull().sum() > 0
missing[missing].index

Index(['children', 'country', 'agent', 'company'], dtype='object')

In [75]:
#Column name
# Missing value count
# Missing value percentage
# for only those columns that have missing values, sorted from highest percentage to lowest.

missing_count = df.isnull().sum() 
columns = missing_count.index
missing_per = (missing_count / len(df) )*100
df_missing = pd.DataFrame({"Columns_Name" : columns , "Missing_count" : missing_count ,"Missing_percentage" :  missing_per})
df_missing[df_missing["Missing_count"] > 0].sort_values(ascending = False , by = "Missing_percentage")

         Columns_Name  Missing_count  Missing_percentage
company       company         112593           94.306893
agent           agent          16340           13.686238
country       country            488            0.408744
children     children              4            0.003350

In [79]:
# top 10 columns with the highest number of unique values.
df.nunique().sort_values(ascending = False).head(10)

adr                               8879
reservation_status_date            926
lead_time                          479
company                            352
agent                              333
country                            177
days_in_waiting_list               128
previous_bookings_not_canceled      73
arrival_date_week_number            53
stays_in_week_nights                35
dtype: int64

In [91]:
# all columns that have only one unique value.
unique = df.nunique() == 1
unique[unique].index

Index([], dtype='object')

In [98]:
# all categorical (object) columns and display how many unique values each categorical column has.
columns = df.select_dtypes(include = ["object"]).columns
unique_count = df.select_dtypes(include = ["object"]).nunique()
df_unique = pd.DataFrame({"Column Name" : columns , "Unique Count" : unique_count})
df_unique.sort_values(ascending = False , by = "Unique Count")

                                     Column Name  Unique Count
reservation_status_date  reservation_status_date           926
country                                  country           177
assigned_room_type            assigned_room_type            12
arrival_date_month            arrival_date_month            12
reserved_room_type            reserved_room_type            10
market_segment                    market_segment             8
distribution_channel        distribution_channel             5
meal                                        meal             5
customer_type                      customer_type             4
deposit_type                        deposit_type             3
reservation_status            reservation_status             3
hotel                                      hotel             2

In [105]:
# all categorical (object) columns that have more than 10 unique values.
object_df = df.select_dtypes(include = ["object"])
greater_10 = object_df.nunique() > 10
greater_10[greater_10].index

Index(['arrival_date_month', 'country', 'assigned_room_type',
       'reservation_status_date'],
      dtype='object')

In [111]:
# all numerical columns that have more than 100 unique values.
df_number = df.select_dtypes(include = ["number"])
num_gt_100 = df_number.nunique() > 100
num_gt_100[num_gt_100].index

Index(['lead_time', 'agent', 'company', 'days_in_waiting_list', 'adr'], dtype='object')

In [119]:
# summary table for all numerical columns containing:
# Column Name
# Data Type
# Unique Values
# Missing Count
df_number = df.select_dtypes(include = ["number"])
Data_Types = df_number.dtypes
unique = df_number.nunique()
missing = df_number.isnull().sum()
df_numbers = pd.DataFrame({"Data Type" : Data_Types , "Unique Values" : unique , "Missing Count" : missing})
print(df_numbers)

                               Data Type  Unique Values  Missing Count
is_canceled                        int64              2              0
lead_time                          int64            479              0
arrival_date_year                  int64              3              0
arrival_date_week_number           int64             53              0
arrival_date_day_of_month          int64             31              0
stays_in_weekend_nights            int64             17              0
stays_in_week_nights               int64             35              0
adults                             int64             14              0
children                         float64              5              4
babies                             int64              5              0
is_repeated_guest                  int64              2              0
previous_cancellations             int64             15              0
previous_bookings_not_canceled     int64             73              0
booking_changes                    int64             21              0
agent                            float64            333          16340
company                          float64            352         112593
days_in_waiting_list               int64            128              0
adr                              float64           8879              0
required_car_parking_spaces        int64              5              0
total_of_special_requests          int64              6              0

In [128]:
# summary table for all categorical columns containing:

# Column Name
# Data Type
# Unique Values
# Missing Count
# Missing Percentage
df_object = df.select_dtypes(include = ["object"])
columns = df_object.columns
d_type = df_object.dtypes
unique = df_object.nunique()
missing = df_object.isnull().sum()
missing_percentage = (( missing / len(df_object) ) * 100 ).round(2)
df_objects = pd.DataFrame({"Column Name" : columns , "Data Type" : d_type , "Unique Values" : unique , "Missing Count" : missing , "Missing Percentage" : missing_percentage})
df_objects.sort_values(ascending = False , by = "Missing Percentage")

,Column Name,Data Type,Unique Values,Missing Count,Missing Percentage
country,country,object,177,488,0.41
hotel,hotel,object,2,0,0.00
arrival_date_month,arrival_date_month,object,12,0,0.00
meal,meal,object,5,0,0.00
market_segment,market_segment,object,8,0,0.00
distribution_channel,distribution_channel,object,5,0,0.00
reserved_room_type,reserved_room_type,object,10,0,0.00
assigned_room_type,assigned_room_type,object,12,0,0.00
deposit_type,deposit_type,object,3,0,0.00
customer_type,customer_type,object,4,0,0.00
reservation_status,reservation_status,object,3,0,0.00
reservation_status_date,reservation_status_date,object,926,0,0.00

In [137]:
# summary table for all columns (numerical + categorical) containing:

# Column Name
# Data Type
# Unique Values
# Missing Count
# Missing Percentage
# Cardinality (High / Low)
df_num_obj = df.select_dtypes(include = ["object" , "number"])
columns = df_num_obj.columns
d_type = df_num_obj.dtypes
unique = df_num_obj.nunique()
missing = df_num_obj.isnull().sum()
missing_percentage = ((missing / len(df_num_obj))*100).round(2) 
df_num_objs = pd.DataFrame({"Column Name" : columns , "Data Type" : d_type ,
                            "Unique Values" : unique , "Missing Count" : missing , 
                            "Missing Percentage" : missing_percentage})
df_num_objs["Cardinality"] = np.where(df_num_objs["Unique Values"] > 10 , "High" , "Low")
df_num_objs

,Column Name,Data Type,Unique Values,Missing Count,Missing Percentage,Cardinality
hotel,hotel,object,2,0,0.00,Low
is_canceled,is_canceled,int64,2,0,0.00,Low
lead_time,lead_time,int64,479,0,0.00,High
arrival_date_year,arrival_date_year,int64,3,0,0.00,Low
arrival_date_month,arrival_date_month,object,12,0,0.00,High
arrival_date_week_number,arrival_date_week_number,int64,53,0,0.00,High
arrival_date_day_of_month,arrival_date_day_of_month,int64,31,0,0.00,High
stays_in_weekend_nights,stays_in_weekend_nights,int64,17,0,0.00,High
stays_in_week_nights,stays_in_week_nights,int64,35,0,0.00,High
adults,adults,int64,14,0,0.00,High
children,children,float64,5,4,0.00,Low
babies,babies,int64,5,0,0.00,Low
meal,meal,object,5,0,0.00,Low
country,country,object,177,488,0.41,High
market_segment,market_segment,object,8,0,0.00,Low
distribution_channel,distribution_channel,object,5,0,0.00,Low
is_repeated_guest,is_repeated_guest,int64,2,0,0.00,Low
previous_cancellations,previous_cancellations,int64,15,0,0.00,High
previous_bookings_not_canceled,previous_bookings_not_canceled,int64,73,0,0.00,High
reserved_room_type,reserved_room_type,object,10,0,0.00,Low
assigned_room_type,assigned_room_type,object,12,0,0.00,High
booking_changes,booking_changes,int64,21,0,0.00,High
deposit_type,deposit_type,object,3,0,0.00,Low
agent,agent,float64,333,16340,13.69,High
company,company,float64,352,112593,94.31,High
days_in_waiting_list,days_in_waiting_list,int64,128,0,0.00,High
customer_type,customer_type,object,4,0,0.00,Low
adr,adr,float64,8879,0,0.00,High
required_car_parking_spaces,required_car_parking_spaces,int64,5,0,0.00,Low
total_of_special_requests,total_of_special_requests,int64,6,0,0.00,Low
reservation_status,reservation_status,object,3,0,0.00,Low
reservation_status_date,reservation_status_date,object,926,0,0.00,High